server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: on
  datasource:
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/openapi
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher


logging:
  level:
    root: info
    by.mikhalevich.architecture: debug



